2022-06-21 01:21:15,570 Downloading and reading train artifact
wandb: ERROR Project ivopdm/exercise_14 does not contain artifact: "segregated_data_train.csv:latest"
Traceback (most recent call last):
  File "/Users/ivopdm/.conda/envs/mlflow-4024711ee7c81427e4f3461efa20a2017b5d781f/lib/python3.8/site-packages/wandb/apis/normalize.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/Users/ivopdm/.conda/envs/mlflow-4024711ee7c81427e4f3461efa20a2017b5d781f/lib/python3.8/site-packages/wandb/apis/public.py", line 520, in artifact
    artifact = Artifact(self.client, entity, project, artifact_name)
  File "/Users/ivopdm/.conda/envs/mlflow-4024711ee7c81427e4f3461efa20a2017b5d781f/lib/python3.8/site-packages/wandb/apis/public.py", line 2583, in __init__
    self._load()
  File "/Users/ivopdm/.conda/envs/mlflow-4024711ee7c81427e4f3461efa20a2017b5d781f/lib/python3.8/site-packages/wandb/apis/public.py", line 3097, in _load
    raise ValueError(
ValueError: Project ivopdm/exercise_14 does not contain artifact: "segregated_data_train.csv:latest"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 263, in <module>
    go(args)
  File "run.py", line 33, in go
    train_data_path = run.use_artifact(args.train_data).file()
  File "/Users/ivopdm/.conda/envs/mlflow-4024711ee7c81427e4f3461efa20a2017b5d781f/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1957, in use_artifact
    artifact = public_api.artifact(type=type, name=name)
  File "/Users/ivopdm/.conda/envs/mlflow-4024711ee7c81427e4f3461efa20a2017b5d781f/lib/python3.8/site-packages/wandb/apis/normalize.py", line 62, in wrapper
    six.reraise(CommError, CommError(message, err), sys.exc_info()[2])
  File "/Users/ivopdm/.conda/envs/mlflow-4024711ee7c81427e4f3461efa20a2017b5d781f/lib/python3.8/site-packages/six.py", line 718, in reraise
    raise value.with_traceback(tb)
  File "/Users/ivopdm/.conda/envs/mlflow-4024711ee7c81427e4f3461efa20a2017b5d781f/lib/python3.8/site-packages/wandb/apis/normalize.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/Users/ivopdm/.conda/envs/mlflow-4024711ee7c81427e4f3461efa20a2017b5d781f/lib/python3.8/site-packages/wandb/apis/public.py", line 520, in artifact
    artifact = Artifact(self.client, entity, project, artifact_name)
  File "/Users/ivopdm/.conda/envs/mlflow-4024711ee7c81427e4f3461efa20a2017b5d781f/lib/python3.8/site-packages/wandb/apis/public.py", line 2583, in __init__
    self._load()
  File "/Users/ivopdm/.conda/envs/mlflow-4024711ee7c81427e4f3461efa20a2017b5d781f/lib/python3.8/site-packages/wandb/apis/public.py", line 3097, in _load
    raise ValueError(
wandb.errors.error.CommError: Project ivopdm/exercise_14 does not contain artifact: "segregated_data_train.csv:latest"
